Add option to ignore CSS files starting with _
whoisvadym/eleventy-plugin-postcss pull request #9
Opened 2023-01-15 21:33 UTC by florianeckerstorfer

Hey, first thanks for the great plugin. Works, like a charm.

In my setup I use `postcss-import` and I use the convention to start imported files with an underscore (which I think is quite common). To keep my final build clean, I don't want these included files out of my final build, so I added an option to the plugin to ignore files that start with an underscore.

You would use the option like this:
```js
// Import the plugin
const PostCSSPlugin = require("eleventy-plugin-postcss");

module.exports = (config) => {
    // Enable the plugin in you project
    config.addPlugin(PostCSSPlugin, { ignoreUnderscore: true });
}
```

I think this would also close #7

2023-01-19 04:05 UTC, vdmzln commented
Hi @florianeckerstorfer,
Thanks for your feedback and your Pull Request. I'll review your changes and will get back to you asap.

2023-01-19 09:51 UTC, florianeckerstorfer commented
@whoisvadym Let me know if there are any tests I should add

2023-01-30 03:02 UTC, whoisvadym requested changes
Hi @florianeckerstorfer, thanks for taking the time to contribute to this project. I approved the pipeline, and it looks like one formatting issue needs a resolution. Please take a look at a code review for more details.

2023-01-30 03:02 UTC, whoisvadym commented on README.md
> +If you want to ignore CSS files that start with `_` to be processed, you can pass the `ignoreUnderscore` option to the plugin:
Thanks for updating the readme!

2023-01-30 03:02 UTC, whoisvadym commented on src/extension.js
> +        && path.basename(page.inputPath).match(/^_/)
I think it would be more flexible to let developers provide the pattern for matching in case someone has a different naming convention for files that they would like to exclude. So something like `pluginOptions.ignorePattern` or `pluginOptions.ignoreRegex`. What do you think?

2023-01-30 03:02 UTC, whoisvadym commented on src/extension.js
> +        pluginOptions.ignoreUnderscore
Please address the pipeline failure (`Trailing spaces not allowed`)

2023-01-30 03:02 UTC, whoisvadym commented on .eleventy.js
> +const extension = require('./src/extension');
👍

2023-01-30 03:02 UTC, whoisvadym commented on README.md
> +    config.addPlugin(PostCSSPlugin, { ignoreUnderscore: true });
Please add the use case for the new ignore functionality in the integration tests.

2023-01-30 03:02 UTC, whoisvadym commented on src/extension.js
> +module.exports = (pluginOptions = {}) => ({
This should also fall back to a `DEFAULT_PLUGIN_OPTIONS`.

2023-02-03 16:26 UTC, florianeckerstorfer commented
Hey @whoisvadym, thanks for the feedback. I fixed the formatting issues and renamed the option to `ignorePattern`. I also added a test case to the integration test, but based on how the tests are currently set up, it is tricky to check different values for the option

2025-01-23 18:58 UTC, whoisvadym commented
After considering this further, I'm going to close this PR. For the sake of simplicity, I'd like to avoid bringing any sort customization into this plugin unless absolutely necessary. 

In most basic scenarios excluding certain files can be as simple as slightly changing the project structure. ([Example](https://github.com/whoisvadym/eleventy-plugin-postcss/issues/7#issuecomment-2610620498))

Please feel free to [Open a new Issue](https://github.com/whoisvadym/eleventy-plugin-postcss/issues/new/) if you think your use-case requires ignoring the files at plugin level.

2025-01-23 18:58 UTC, closed without merging